Repository CovOpen/CovMapper, pull requests merged in 2020-10, with the labels that each got.

#187 fix: clickables pages
  apps/official/components/CovMapFeatureInfo.tsx
  apps/official/components/basic-recommendations/BasicRecommendations.tsx
  apps/official/components/pages/ContactBehavior.tsx
  apps/official/components/pages/RKI.tsx
  apps/official/components/risk-levels-page/RiskLevelsPage.tsx
  apps/official/components/risk-recommendation/RiskRecommendation.tsx
  yarn.lock
Labels: question

#191 chore: fix pr-title check
  .github/workflows/pr-title-check.yml
Labels: LGTM

#195 fix: add google description meta tag
  src/index.ejs
Labels: LGTM

#194 chore: add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: LGTM

#178 add download script for updating app sources
  hosting/download.sh
Labels: question

#230 fix: shows last selected feature after page reload
  apps/official/index.ts
  src/app-config.types.ts
  src/components/CovMap.tsx
  src/state/app.ts
  src/state/thunks/flyTo.ts
Labels: LGTM, enhancement

#243 fix: move searchbar to navbar
  src/App.tsx
  src/components/CovMap.tsx
  src/components/NavBar.tsx
Labels: LGTM, bug

#266 fix: avoid creating multiple service worker instances
  src/components/ServiceWorker.tsx
Labels: LGTM, bug

#270 fix: date offset and auto progress date
  apps/official/index.ts
  dev/generate-random-data-for-geojson.js
  src/App.tsx
  src/app-config.types.ts
  src/components/AutoProgressDate.tsx
  src/components/CovMap.tsx
  src/components/FeatureInfo.tsx
  src/components/Legend.tsx
  src/components/TimeNav.tsx
  src/components/TimeRangeSlider.tsx
  src/components/Visual.tsx
  src/lib/diff-days.ts
  src/lib/formatUTCDate.js
  src/lib/formatUTCDate.ts
  src/state/app.ts
  src/state/thunks/fetchMappedSet.ts
Labels: LGTM, enhancement

#310 fix: avoid fetching data/geojson multiple times
  src/state/thunks/fetchMappedSet.ts
Labels: bug
